development:
  adapter: postgresql
  encoding: unicode
  database: blogger3
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: blogger3
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  url: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

