development:
  adapter: postgresql
  encoding: unicode
  database: blogger3
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: blogger3
  url: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

